services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=12345678
    #   - MYSQL_DATABASE=react_node_app
    #   - MYSQL_USER=appuser
    #   - MYSQL_PASSWORD=learnIT02#
    # volumes:
    #   - ./db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    depends_on:
      db:
         condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3200/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    networks:
      - app-network

# volumes:
#   db_data:

networks:
  app-network:
