
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=react_node_app
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=learnIT02#
    # volumes:
      # - ./db_data:/var/lib/mysql
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=appuser
    #   - DB_PASSWORD=learnIT02#
    #   - DB_NAME=react_node_app
    depends_on:
      - db
    networks:
      - app-network
# volumes:
#   db_data:

networks:
  app-network:
