services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "appuser", "-p${MYSQL_PASSWORD}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    depends_on:
      db:
         condition: service_healthy
    networks:
      - app-network

# volumes:
#   db_data:

networks:
  app-network:
