FROM node:18-alpine

# Install curl
RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .env.example .env
COPY . ./

EXPOSE 3200

CMD ["node", "server.js"]
